steps:
  clippy:
    name: Clippy
    image: docker.io/rust:latest
    environment:
      NIX_AFFINITY_HACK: 0
    depends_on: []
    commands:
      - curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install linux
        --extra-conf "sandbox = false"
        --init none
        --no-confirm
      - . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
      - cargo install cargo-hack
      - nix develop --impure -c cargo hack --each-feature --all clippy -- -D warnings

  fmt:
    name: Formatting
    image: docker.io/rust:latest
    environment:
      NIX_AFFINITY_HACK: 0
    depends_on: []
    commands:
      - curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install linux
        --extra-conf "sandbox = false"
        --init none
        --no-confirm
      - . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
      - nix develop --impure -c cargo fmt --all -- --check

  test:
    name: Test
    image: docker.io/rust:latest
    environment:
      NIX_AFFINITY_HACK: 0
      DATABASE_URL: "postgres://postgres:postgres@postgres/test_db"
      MINIO_URL: "http://minio:9000"
      REDIS_URL: "redis://redis"
    depends_on: [Clippy, Formatting]
    commands:
      - curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install linux
        --extra-conf "sandbox = false"
        --init none
        --no-confirm
      - . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
      - cargo install cargo-nextest
      - nix develop --impure --command bash -c "unset LD_LIBRARY_PATH && cargo nextest run --all-features"

services:
  - name: postgres
    image: docker.io/postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
  - name: minio
    image: docker.io/bitnami/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
  - name: redis
    image: docker.io/redis:latest