when:
  - branch: [dev/woodpecker]
  - event: [push, pull_request]

steps:
  clippy:
    name: Clippy
    image: ghcr.io/perillamint/nix-testcontainer
    environment:
      NIX_AFFINITY_HACK: 0
      # store cargo data in repo folder so that it gets cached between steps
      CARGO_HOME: .cargo_home
    depends_on: []
    commands:
      - . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
      - nix develop --impure -c cargo hack --each-feature --all clippy -- -D warnings

  fmt:
    name: Formatting
    image: ghcr.io/perillamint/nix-testcontainer
    environment:
      NIX_AFFINITY_HACK: 0
      # store cargo data in repo folder so that it gets cached between steps
      CARGO_HOME: .cargo_home
    depends_on: []
    commands:
      - . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
      - nix develop --impure -c cargo fmt --all -- --check

  test:
    name: Test
    image: ghcr.io/perillamint/nix-testcontainer
    environment:
      NIX_AFFINITY_HACK: 0
      # store cargo data in repo folder so that it gets cached between steps
      CARGO_HOME: .cargo_home
      DATABASE_URL: "postgres://postgres:postgres@postgres/test_db"
      MINIO_URL: "http://minio:9000"
      REDIS_URL: "redis://redis"
    depends_on: [Clippy, Formatting]
    commands:
      - . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
      - nix develop --impure --command bash -c "unset LD_LIBRARY_PATH && cargo nextest run --all-features"

services:
  - name: postgres
    image: docker.io/postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
  - name: minio
    image: docker.io/bitnami/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
  - name: redis
    image: docker.io/redis:latest